spring:
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info