server:
  port: 8886
spring:
#    sleuth:
#      sampler:
#         percentage:  1
  sleuth:
    sampler:
      probability: 1.0
  zipkin:
   baseUrl: http://localhost:9411
      #     service:
      #       name: zipkin
   sender:
     type: web
  cloud:
    stream:
      bindings:
        inboundOrgChanges:
          destination: orgChangeTopic
          content-type: application/json
          group: licensingGroup
        kafka:
          binder:
            zkNodes: localhost
            brokers: localhost
  datasource:
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true


#        input:
#          destination: orgChangeTopic
#          content-type: application/json
#          group: licensingGroup

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

#Setting logging levels
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    com.thoughtmechanix: DEBUG
